# -*- coding: utf-8 -*-
"""Maincode.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QVTs70DkThqYnihhYDbeE-lC2Ni0duFS
"""

from tkinter import *
from PIL import Image,ImageTk
from tkinter import messagebox
import pymysql

root=Tk()
root.title("BUS RESERVATION SYSTEM")
root.geometry("500x700")
Label(root,text="BUS RESERVATION FORM",width=25,
      font=("airal",20,"bold"),
      relief="solid").pack()
image=Image.open("download.jpg")
photo=ImageTk.PhotoImage(image)
Label(root,image=photo).place(x=150,y=50)
Label(root,text="TRAVELLER NAME",width=20,
      font=("airal",10,"bold"),
      relief="solid").place(x=50,y=250)
name=StringVar()
Entry(root,textvariable=name).place(x=300,y=250)
Label(root,text="TRAVELLER EMAIL",width=25,
      font=("airal",10,"bold"),
      relief="solid").place(x=50,y=290)
eml=StringVar()
Entry(root,textvariable=eml).place(x=300,y=290)
Label(root,text="TRAVELLING FROM",width=25,
      font=("airal",10,"bold"),
      relief="solid").place(x=50,y=330)
ec=StringVar(root)
ec.set("TRAVELLING FROM")
OptionMenu(root, ec,"DELHI","GURUGRAM","NOIDA","GHAZIABAD","ROHTAK","HARIDWAR").place(x=300,y=325)
Label(root,text="TRAVELLING TO",width=25,
      font=("airal",10,"bold"),
      relief="solid").place(x=50,y=360)
wc=StringVar(root)
wc.set("TRAVELLING TO")
OptionMenu(root, wc,"DELHI","GURUGRAM","NOIDA","GHAZIABAD","ROHTAK","HARIDWAR").place(x=300,y=358)
Label(root,text="DATE(dd/mm/yyyy)",width=20,
      font=("airal",10,"bold"),
      relief="solid").place(x=50,y=398)
date=StringVar()
Entry(root,textvariable=date).place(x=300,y=398)
Label(root,text="TRAVELLER GENDER",width=25,
      font=("airal",10,"bold"),
      relief="solid").place(x=50,y=440)
var1=IntVar()
var2=IntVar()
Checkbutton(root, text = "male",
            variable = var1,
            onvalue = 1,
            offvalue = 0).place(x=300,y=440)
Checkbutton(root,text="female",
            variable = var2,
            onvalue = 1,
            offvalue = 0).place(x=380,y=440)
Label(root,text="TYPE OF BUS",width=25,
      font=("airal",10,"bold"),
      relief="solid").place(x=50,y=480)
var=IntVar()
Radiobutton(root,text="AC",
            variable=var,value=1).place(x=300,y=480)
Radiobutton(root,text="NON AC",
            variable=var,value=2).place(x=380,y=480)
def new():
    r1=Tk()
    r1.mainloop()
menubar=Menu(root)
file=Menu(menubar,tearoff=0)
menubar.add_cascade(label="file",menu=file)
file.add_command(label="new file",command=new)
file.add_command(label="edit",command=None)
file.add_command(label="help",command=None)
file.add_separator()
file.add_command(label="exit",command=root.destroy)

edit=Menu(menubar,tearoff=0)
menubar.add_cascade(label="edit",menu=edit)
edit.add_command(label="edit file",command=None)
edit.add_command(label="edit info",command=None)
edit.add_command(label="help",command=None)
edit.add_separator()
edit.add_command(label="exit",command=root.destroy)
root.config(menu=menubar)

def submit():
    nm=name.get()
    email=eml.get()
    frm=ec.get()
    to=wc.get()
    dte=date.get()
    ch=var.get()
    mode={1:"AC",2:"NON-AC"}
    gen=""
    if Checkvar1.get()==1:
        gen=gen+"MALE"
    elif Checkvar2.get()==2:
        gen=gen+"FEMALE"
    messagebox.showinfo("APPLICATION STATUS",message="APPLICATION SUCCESSFUL")
    conn=pymysql.connect("localhost","root","","project")
    cur=conn.cursor()
    q="insert into backscreen1 values(%s,%s,%s,%s,%s,%s,%s)"
    val=(nm,email,frm,to,dte,mode[ch],gen)
    cur.execute(q,val)
    conn.commit()
    conn.close()
    
def exit():
     root.destroy()
Button(root,text="SUBMIT INFO",width=15,
      font=("airal",10,"bold"),
      relief="solid",command=submit).place(x=150,y=600)
Button(root,text="EXIT",width=15,
      font=("airal",10,"bold"),
      relief="solid",command=exit).place(x=300,y=600)
root.resizable(0,0)
root.mainloop()